import { GradeItem, DiaryEntry, IncidentRecord, Announcement, EnrollmentRecord, FinancialSummary } from '../types';

export const INITIAL_GRADES_6A: GradeItem[] = [
  {
    studentId: 'aluno-01',
    studentName: 'Lucas Mendes',
    matricula: '2024.6A.014',
    p1: 8.5,
    trabalho: 9.0,
    p2: 8.0,
    recuperacao: null,
    media: 8.5,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-02',
    studentName: 'Ana Beatriz Souza Ribeiro',
    matricula: '2024.6A.001',
    p1: 9.5,
    trabalho: 10.0,
    p2: 9.0,
    recuperacao: null,
    media: 9.5,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-03',
    studentName: 'Bernardo Guimarães Ramos',
    matricula: '2024.6A.002',
    p1: 5.5,
    trabalho: 6.0,
    p2: 5.0,
    recuperacao: 6.5,
    media: 5.5,
    situacao: 'em_recuperacao',
  },
  {
    studentId: 'aluno-04',
    studentName: 'Camila Albuquerque Viana',
    matricula: '2024.6A.003',
    p1: 7.5,
    trabalho: 8.0,
    p2: 7.0,
    recuperacao: null,
    media: 7.5,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-05',
    studentName: 'Davi Lucca Sanches',
    matricula: '2024.6A.004',
    p1: 4.0,
    trabalho: 5.0,
    p2: 4.5,
    recuperacao: null,
    media: 4.5,
    situacao: 'reprovado',
  },
  {
    studentId: 'aluno-06',
    studentName: 'Enzo Gabriel Castro',
    matricula: '2024.6A.005',
    p1: 8.0,
    trabalho: 8.5,
    p2: 7.5,
    recuperacao: null,
    media: 8.0,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-07',
    studentName: 'Gabriela Meireles Santos',
    matricula: '2024.6A.006',
    p1: 9.0,
    trabalho: 9.5,
    p2: 9.0,
    recuperacao: null,
    media: 9.2,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-08',
    studentName: 'Heitor Nogueira Barreto',
    matricula: '2024.6A.007',
    p1: 6.0,
    trabalho: 7.0,
    p2: 6.5,
    recuperacao: null,
    media: 6.5,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-09',
    studentName: 'Isabela Fontoura Lima',
    matricula: '2024.6A.008',
    p1: 8.5,
    trabalho: 9.0,
    p2: 9.0,
    recuperacao: null,
    media: 8.8,
    situacao: 'aprovado',
  },
  {
    studentId: 'aluno-10',
    studentName: 'João Pedro Toledo',
    matricula: '2024.6A.009',
    p1: 7.0,
    trabalho: 7.5,
    p2: 7.0,
    recuperacao: null,
    media: 7.2,
    situacao: 'aprovado',
  },
];

export const INITIAL_DIARY_ENTRIES: DiaryEntry[] = [
  {
    id: 'diary-01',
    classId: 'turma-6a',
    className: '6º Ano A',
    subject: 'Língua Portuguesa',
    date: '2026-08-14',
    title: 'Gêneros Textuais: Crônica Narrativa e Linguagem Coloquial',
    content: 'Análise de crônicas de Fernando Sabino e Rubem Braga. Discussão sobre a representação do cotidiano e recursos de ironia e humor. Prática de produção textual em duplas.',
    bnccCodes: ['EF69LP44', 'EF69LP47', 'EF69LP53'],
    homework: 'Redigir uma crônica de 20 a 30 linhas sobre um fato ocorrido na praia de Grussaí.',
    resourcesUsed: 'Livro didático pág. 112-118, projetor multimídia, textos impressos.',
    createdAt: '14/08/2026 às 11:20',
  },
  {
    id: 'diary-02',
    classId: 'turma-6a',
    className: '6º Ano A',
    subject: 'Língua Portuguesa',
    date: '2026-08-12',
    title: 'Sintaxe: Sujeito e Predicado — Estrutura e Classificação',
    content: 'Introdução aos termos essenciais da oração. Identificação de sujeito simples, composto, oculto e indeterminado em manchetes de jornais locais.',
    bnccCodes: ['EF06LP06', 'EF06LP07'],
    homework: 'Exercícios da apostila páginas 45 a 48.',
    resourcesUsed: 'Quadro interativo e recortes de notícias do Norte Fluminense.',
    createdAt: '12/08/2026 às 10:15',
  },
  {
    id: 'diary-03',
    classId: 'turma-7b',
    className: '7º Ano B',
    subject: 'Língua Portuguesa',
    date: '2026-08-13',
    title: 'Figuras de Linguagem: Metáfora, Metonímia e Personificação',
    content: 'Estudo das figuras de palavras e de pensamento a partir de canções populares brasileiras e poemas modernistas.',
    bnccCodes: ['EF69LP54', 'EF07LP02'],
    homework: 'Encontrar 3 exemplos de metáfora em letras de músicas de sua preferência.',
    resourcesUsed: 'Caixa de som bluetooth, slides e material complementar.',
    createdAt: '13/08/2026 às 09:40',
  },
];

export const INITIAL_INCIDENTS: IncidentRecord[] = [
  {
    id: 'inc-01',
    studentId: 'aluno-03',
    studentName: 'Bernardo Guimarães Ramos',
    classId: 'turma-6a',
    className: '6º Ano A',
    type: 'atraso',
    severity: 'baixa',
    title: 'Atraso de 20 minutos na 1ª aula',
    description: 'Aluno chegou às 07:50 alegando retenção no transporte escolar em Grussaí. Entrada autorizada pela coordenação.',
    reportedBy: 'Profª Helena Fontes',
    reportedRole: 'Docente',
    date: '14/08/2026',
    resolved: true,
    notifiedParents: true,
  },
  {
    id: 'inc-02',
    studentId: 'aluno-05',
    studentName: 'Davi Lucca Sanches',
    classId: 'turma-6a',
    className: '6º Ano A',
    type: 'comportamental',
    severity: 'media',
    title: 'Uso de smartphone durante explicação',
    description: 'Aluno foi advertido verbalmente duas vezes sobre o uso de celular com fones durante a atividade em grupo.',
    reportedBy: 'Profª Helena Fontes',
    reportedRole: 'Docente',
    date: '13/08/2026',
    resolved: false,
    notifiedParents: true,
  },
  {
    id: 'inc-03',
    studentId: 'aluno-01',
    studentName: 'Lucas Mendes',
    classId: 'turma-6a',
    className: '6º Ano A',
    type: 'elogio',
    severity: 'positiva',
    title: 'Destaque na Olimpíada de Língua Portuguesa',
    description: 'Lucas obteve a melhor pontuação da turma na fase preparatória regional com excelente domínio de argumentação.',
    reportedBy: 'Profª Helena Fontes',
    reportedRole: 'Docente',
    date: '12/08/2026',
    resolved: true,
    notifiedParents: true,
  },
  {
    id: 'inc-04',
    studentId: 'aluno-02',
    studentName: 'Ana Beatriz Souza Ribeiro',
    classId: 'turma-6a',
    className: '6º Ano A',
    type: 'elogio',
    severity: 'positiva',
    title: 'Monitoria Voluntária de Colegas',
    description: 'Ana auxiliou ativamente seus colegas de bancada com paciência e clareza durante as atividades práticas.',
    reportedBy: 'Profª Helena Fontes',
    reportedRole: 'Docente',
    date: '10/08/2026',
    resolved: true,
    notifiedParents: false,
  },
];

export const MOCK_ANNOUNCEMENTS: Announcement[] = [
  {
    id: 'ann-01',
    title: 'Feira de Ciências & Inovação CEPI 2026',
    category: 'evento',
    summary: 'Convidamos toda a comunidade escolar para o encerramento da Semana da Ciência com projetos sobre sustentabilidade marinha de São João da Barra.',
    date: '28 de Agosto, às 09:00',
    author: 'Coordenação Pedagógica',
    targetAudience: ['todos'],
    priority: 'destaque',
  },
  {
    id: 'ann-02',
    title: 'Conselho de Classe do 2º Bimestre',
    category: 'pedagogico',
    summary: 'Reunião de alinhamento com corpo docente e coordenação para fechamento das notas e estratégias de apoio aos alunos.',
    date: '21 de Agosto, às 17:30',
    author: 'Diretoria Pedagógica',
    targetAudience: ['professores'],
    priority: 'alta',
  },
  {
    id: 'ann-03',
    title: 'Reunião de Pais e Mestres — 2º Bimestre',
    category: 'institucional',
    summary: 'Entrega dos boletins impressos e atendimento individualizado com os professores de cada componente curricular.',
    date: '23 de Agosto, das 08h às 12h',
    author: 'Secretaria Escolar',
    targetAudience: ['pais'],
    priority: 'normal',
  },
];

export const MOCK_ENROLLMENTS: EnrollmentRecord[] = [
  {
    id: 'enr-01',
    studentName: 'Mariana Peçanha Barcelos',
    responsibleName: 'Renata Peçanha',
    phone: '(22) 99788-1234',
    email: 'renata.pecanha@gmail.com',
    gradeApplying: '6º Ano Fundamental II',
    status: 'matriculado',
    dateApplied: '15/08/2026',
    monthlyFee: 850,
    hasScholarship: false,
  },
  {
    id: 'enr-02',
    studentName: 'Gabriel Siqueira Freitas',
    responsibleName: 'Marcos Freitas',
    phone: '(22) 99123-9876',
    email: 'marcos.freitas@uol.com.br',
    gradeApplying: '7º Ano Fundamental II',
    status: 'documentacao_pendente',
    dateApplied: '14/08/2026',
    monthlyFee: 850,
    hasScholarship: true,
    scholarshipPercentage: 20,
  },
  {
    id: 'enr-03',
    studentName: 'Beatriz Lemos Cardoso',
    responsibleName: 'Viviane Lemos',
    phone: '(22) 99933-7711',
    email: 'viviane.lemos@gmail.com',
    gradeApplying: '1º Ano Médio',
    status: 'aguardando_vaga',
    dateApplied: '12/08/2026',
    monthlyFee: 1100,
    hasScholarship: false,
  },
];

export const MOCK_FINANCIAL_SUMMARY: FinancialSummary = {
  totalRevenueMonth: 284500,
  paidCount: 298,
  pendingCount: 22,
  overdueCount: 8,
  defaulterRate: 2.4,
  recentPayments: [
    {
      id: 'pay-01',
      studentName: 'Lucas Mendes',
      className: '6º Ano A',
      amount: 850,
      dueDate: '10/08/2026',
      payDate: '08/08/2026',
      status: 'pago',
    },
    {
      id: 'pay-02',
      studentName: 'Ana Beatriz Souza',
      className: '6º Ano A',
      amount: 850,
      dueDate: '10/08/2026',
      payDate: '09/08/2026',
      status: 'pago',
    },
    {
      id: 'pay-03',
      studentName: 'Bernardo Ramos',
      className: '6º Ano A',
      amount: 850,
      dueDate: '10/08/2026',
      status: 'pendente',
    },
    {
      id: 'pay-04',
      studentName: 'Davi Lucca Sanches',
      className: '6º Ano A',
      amount: 850,
      dueDate: '10/08/2026',
      status: 'atrasado',
    },
  ],
};
