import { SchoolClass, Student } from '../types';

export const MOCK_CLASSES: SchoolClass[] = [
  {
    id: 'turma-6a',
    name: '6º Ano A',
    code: 'EF2-6A',
    shift: 'Matutino',
    room: 'Sala 102 - Bloco Amarelo',
    totalStudents: 24,
    gradeLevel: 'Ensino Fundamental II',
    mainTeacherId: 'user-prof-01',
    subjects: ['Língua Portuguesa', 'Matemática', 'Ciências', 'História', 'Geografia', 'Inglês', 'Artes'],
  },
  {
    id: 'turma-7b',
    name: '7º Ano B',
    code: 'EF2-7B',
    shift: 'Matutino',
    room: 'Sala 105 - Bloco Azul',
    totalStudents: 22,
    gradeLevel: 'Ensino Fundamental II',
    mainTeacherId: 'user-prof-01',
    subjects: ['Língua Portuguesa', 'Matemática', 'Ciências', 'História', 'Geografia', 'Inglês', 'Redação'],
  },
  {
    id: 'turma-8a',
    name: '8º Ano A',
    code: 'EF2-8A',
    shift: 'Vespertino',
    room: 'Sala 201 - Bloco Verde',
    totalStudents: 26,
    gradeLevel: 'Ensino Fundamental II',
    mainTeacherId: 'user-prof-01',
    subjects: ['Língua Portuguesa', 'Matemática', 'Física Básica', 'Química Básica', 'História', 'Geografia'],
  },
  {
    id: 'turma-9a',
    name: '9º Ano A',
    code: 'EF2-9A',
    shift: 'Matutino',
    room: 'Sala 204 - Bloco Verde',
    totalStudents: 28,
    gradeLevel: 'Ensino Fundamental II',
    mainTeacherId: 'user-prof-02',
    subjects: ['Língua Portuguesa', 'Matemática', 'Ciências', 'História', 'Geografia', 'Filosofia'],
  },
  {
    id: 'turma-1em',
    name: '1º Ano EM',
    code: 'EM-1A',
    shift: 'Matutino',
    room: 'Sala 301 - Bloco Ouro',
    totalStudents: 30,
    gradeLevel: 'Ensino Médio',
    mainTeacherId: 'user-prof-03',
    subjects: ['Língua Portuguesa', 'Literatura', 'Matemática', 'Física', 'Química', 'Biologia', 'Sociologia'],
  },
];

export const MOCK_STUDENTS_6A: Student[] = [
  {
    id: 'aluno-01',
    name: 'Lucas Mendes',
    matricula: '2024.6A.014',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Carlos Eduardo Mendes',
    responsiblePhone: '(22) 99874-1234',
    responsibleEmail: 'carlos.mendes@gmail.com',
    status: 'ativo',
    birthDate: '14/05/2012',
  },
  {
    id: 'aluno-02',
    name: 'Ana Beatriz Souza Ribeiro',
    matricula: '2024.6A.001',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1517841905240-472988babdf9?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Patrícia Souza',
    responsiblePhone: '(22) 99765-4321',
    responsibleEmail: 'patricia.souza@gmail.com',
    status: 'ativo',
    birthDate: '22/08/2012',
  },
  {
    id: 'aluno-03',
    name: 'Bernardo Guimarães Ramos',
    matricula: '2024.6A.002',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Rodrigo Ramos',
    responsiblePhone: '(22) 99234-5678',
    responsibleEmail: 'rodrigo.ramos@yahoo.com.br',
    status: 'ativo',
    birthDate: '10/01/2012',
  },
  {
    id: 'aluno-04',
    name: 'Camila Albuquerque Viana',
    matricula: '2024.6A.003',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Fernanda Albuquerque',
    responsiblePhone: '(22) 99112-3344',
    responsibleEmail: 'fernanda.viana@hotmail.com',
    status: 'ativo',
    birthDate: '03/11/2012',
  },
  {
    id: 'aluno-05',
    name: 'Davi Lucca Sanches',
    matricula: '2024.6A.004',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1506794778202-cad84cf45f1d?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Marcelo Sanches',
    responsiblePhone: '(22) 99345-6789',
    responsibleEmail: 'marcelo.sanches@outlook.com',
    status: 'ativo',
    birthDate: '19/02/2012',
  },
  {
    id: 'aluno-06',
    name: 'Enzo Gabriel Castro',
    matricula: '2024.6A.005',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1522075469751-3a6694fb2f61?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Juliana Castro',
    responsiblePhone: '(22) 98877-6655',
    responsibleEmail: 'juliana.castro@gmail.com',
    status: 'ativo',
    birthDate: '30/07/2012',
  },
  {
    id: 'aluno-07',
    name: 'Gabriela Meireles Santos',
    matricula: '2024.6A.006',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Renata Meireles',
    responsiblePhone: '(22) 98122-4466',
    responsibleEmail: 'renata.meireles@gmail.com',
    status: 'ativo',
    birthDate: '15/09/2012',
  },
  {
    id: 'aluno-08',
    name: 'Heitor Nogueira Barreto',
    matricula: '2024.6A.007',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1501196354995-cbb51c65aaea?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Guilherme Barreto',
    responsiblePhone: '(22) 99655-4433',
    responsibleEmail: 'guilherme.barreto@gmail.com',
    status: 'ativo',
    birthDate: '05/04/2012',
  },
  {
    id: 'aluno-09',
    name: 'Isabela Fontoura Lima',
    matricula: '2024.6A.008',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1524504388940-b1c1722653e1?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Aline Fontoura',
    responsiblePhone: '(22) 98788-9900',
    responsibleEmail: 'aline.fontoura@gmail.com',
    status: 'ativo',
    birthDate: '12/12/2012',
  },
  {
    id: 'aluno-10',
    name: 'João Pedro Toledo',
    matricula: '2024.6A.009',
    classId: 'turma-6a',
    className: '6º Ano A',
    avatar: 'https://images.unsplash.com/photo-1534308983496-4fabb1a015ee?auto=format&fit=crop&q=80&w=150',
    responsibleName: 'Eduardo Toledo',
    responsiblePhone: '(22) 99444-1122',
    responsibleEmail: 'eduardo.toledo@gmail.com',
    status: 'ativo',
    birthDate: '27/03/2012',
  },
];
