import { UserProfile, UserRole } from '../types';

export const MOCK_USERS: Record<UserRole, UserProfile> = {
  professor: {
    id: 'user-prof-01',
    name: 'Profª Helena Fontes',
    email: 'helena.fontes@pequenaisa.com.br',
    role: 'professor',
    roleTitle: 'Docente de Língua Portuguesa & Literatura',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?auto=format&fit=crop&q=80&w=200',
    department: 'Ensino Fundamental II e Médio',
    schoolUnit: 'Unidade Grussaí',
    activeClass: 'turma-6a',
    classes: ['6º Ano A', '7º Ano B', '8º Ano A'],
    subjects: ['Língua Portuguesa', 'Redação'],
  },
  diretor: {
    id: 'user-dir-01',
    name: 'Drª Marilda S. Guimarães',
    email: 'marilda.diretoria@pequenaisa.com.br',
    role: 'diretor',
    roleTitle: 'Diretora Pedagógica Geral',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?auto=format&fit=crop&q=80&w=200',
    department: 'Diretoria Executiva',
    schoolUnit: 'Unidade Grussaí',
  },
  secretaria: {
    id: 'user-sec-01',
    name: 'Cláudia Rezende Rocha',
    email: 'secretaria.geral@pequenaisa.com.br',
    role: 'secretaria',
    roleTitle: 'Secretária Acadêmica Chefe',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?auto=format&fit=crop&q=80&w=200',
    department: 'Secretaria & Atendimento',
    schoolUnit: 'Unidade Grussaí',
  },
  responsavel: {
    id: 'user-resp-01',
    name: 'Carlos Eduardo Mendes',
    email: 'carlos.mendes@gmail.com',
    role: 'responsavel',
    roleTitle: 'Responsável Financeiro e Pedagógico',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&q=80&w=200',
    schoolUnit: 'Unidade Grussaí',
    studentName: 'Lucas Mendes',
    studentGrade: '6º Ano A - Fundamental II',
  },
  aluno: {
    id: 'user-aluno-01',
    name: 'Lucas Mendes',
    email: 'lucas.mendes@aluno.pequenaisa.com.br',
    role: 'aluno',
    roleTitle: 'Estudante - Matrícula 2024.6A.014',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?auto=format&fit=crop&q=80&w=200',
    schoolUnit: 'Unidade Grussaí',
    activeClass: 'turma-6a',
    studentGrade: '6º Ano A',
  },
};
